//Arrays de imagem, link e nome das Cartas
var listaCartas = [
  "http://1.bp.blogspot.com/-qAuuQIF-HR8/Uavb3bfxy7I/AAAAAAAAAsA/mQ_OK0BVuEI/s320/equilibrio.jpg ",
  "http://1.bp.blogspot.com/-g6G2VMWGk0s/UaveVT0EzEI/AAAAAAAAAsM/0B3hqp28DFw/s320/bendicion.jpg ",
  "http://3.bp.blogspot.com/-m0MewVhqZkY/Uavlup6hc-I/AAAAAAAAAsY/ibrtYQVF7tU/s320/elegancia.jpg ",
  "http://3.bp.blogspot.com/-kTfAEXUOFvI/Uavl3HzggKI/AAAAAAAAAsg/EuAfDOM6PXs/s320/inspiracion.jpg ",
  "http://2.bp.blogspot.com/-J2J4D8lZXu8/Uavl_6CxEZI/AAAAAAAAAso/Az61CGwiufU/s320/coraje.jpg ",
  "http://4.bp.blogspot.com/-nOWmFal6PCw/UaxaKUR7HeI/AAAAAAAAAs4/FUIKcrPMjxo/s320/esperanza.jpg",
  "http://3.bp.blogspot.com/-iH0cRVZ9LGY/UaxhHpRY9LI/AAAAAAAAAtI/UgrT3jLgqoY/s320/integridad.jpg",
  "http://1.bp.blogspot.com/-3fubAuLeIns/UaxhO2DqdcI/AAAAAAAAAtQ/HJsq2BYJFyE/s320/fuerza+de+voluntad.jpg ",
  "http://1.bp.blogspot.com/-s_fWjwXjx8M/UblygxSSKFI/AAAAAAAAAwY/cuF1WVAr_7A/s320/clemencia.jpg ",
  "http://4.bp.blogspot.com/-A8RYCI9PtZo/UblyoL0BhnI/AAAAAAAAAwg/dq4gnesKBwI/s320/alegria.jpg ",
  "http://2.bp.blogspot.com/-rsKV5h1Q6As/Ublz9x2hMbI/AAAAAAAAAww/YR-OTNjwEnA/s320/liberacion.jpg ",
  "http://3.bp.blogspot.com/-OVmJmKaGMAM/Ubl3i8RzBmI/AAAAAAAAAxA/NgLKV3LnaqU/s320/meditacion.jpg ",
  "http://2.bp.blogspot.com/-i9BVy2fZUU8/Ubmv26DeGFI/AAAAAAAAAxQ/FWzhxnICdmE/s320/inteligencia+divina.jpg ",
  "http://1.bp.blogspot.com/-Rm3DrCFm6nE/Ubmv-Ly84dI/AAAAAAAAAxY/1EDWTQE9SXA/s320/misericordia.jpg",
  "http://2.bp.blogspot.com/-mP9udir-RIM/UbmwayvK3tI/AAAAAAAAAxg/zPMwoxSo5CA/s320/milagros.jpg ",
  "http://2.bp.blogspot.com/-C9eKYnjeITg/UboWsWc5ZuI/AAAAAAAAAxw/5zpDb-cNqic/s320/sabiduria.jpg ",
  "http://2.bp.blogspot.com/-zuTWZ8IFdzI/UboZvrfZ32I/AAAAAAAAAyA/fRmj7KO8uwk/s320/encantamiento.jpg ",
  "http://3.bp.blogspot.com/-OQoMtoo-JnQ/Ub2k5XQsV_I/AAAAAAAAA2o/RxWdaLEZq1w/s320/yo+soy+presencia.jpg ",
  "http://1.bp.blogspot.com/-OTVqQBX95FM/Ub2mf3SXsII/AAAAAAAAA24/JTPl-jkLpM0/s320/trasmutacion.jpg ",
  "http://2.bp.blogspot.com/-x8MRJplyK94/Ub2mp7J_XZI/AAAAAAAAA3A/UpH1p2PTsz8/s320/paciencia.jpg ",
  "http://2.bp.blogspot.com/-DdC35Ipiimc/Ub4nTm1eWzI/AAAAAAAAA3g/JfGfJgAIYas/s320/limpieza.jpg ",
  "http://4.bp.blogspot.com/-Som6FMqJm-k/Ub4nL11oQdI/AAAAAAAAA3Y/YgMrRrmpOkU/s320/comunion.jpg ",
  "http://2.bp.blogspot.com/-AMRE5LX0mOo/Ub4mvMHdO1I/AAAAAAAAA3Q/KHPIJCltw6w/s320/la+fuerza+de+la+tierra.jpg ",
  "http://2.bp.blogspot.com/-dkW3ICSYzX0/Ub9Ss6Op-lI/AAAAAAAAA3w/V0mwG5KN73E/s320/empatia.jpg",
  "http://4.bp.blogspot.com/-xQchvY7Jsy0/Ub_01GJrW2I/AAAAAAAAA4A/U6mesUkc47A/s320/sue%C3%B1os.jpg",
  "http://2.bp.blogspot.com/-SPbHbbsg6bg/UcBBhvIuvfI/AAAAAAAAA4Q/J9rdKpUUIAE/s320/fe.jpg",
  "http://1.bp.blogspot.com/-Fg5xKzj2us0/UcGaFQWa8uI/AAAAAAAAA6I/XX2uuw2Pgsg/s320/intuicion.jpg",
  "http://4.bp.blogspot.com/-l-rOsOrPRXE/UcCbkQx334I/AAAAAAAAA4g/EZjSEe6Cs34/s320/retiro.jpg",
  "http://4.bp.blogspot.com/-kV1JB12KE6Y/UcChPyiXMQI/AAAAAAAAA4w/edr-tQxPKHU/s320/evolucion.jpg",
  "http://3.bp.blogspot.com/-WL90golqJ3Y/UcChZ3pV9dI/AAAAAAAAA44/m4bQPNGTX_c/s320/intencion.jpg",
  "http://4.bp.blogspot.com/-pSc8vfzVSvc/UcFOnHJsGPI/AAAAAAAAA5I/N3bgvYTydl4/s320/amor.jpg",
  "http://1.bp.blogspot.com/-cIdYtA9X94w/UcFQhnpWNqI/AAAAAAAAA5Y/4YTRWa7tVQ8/s320/ciclos+planetarios.jpg",
  "http://1.bp.blogspot.com/-lFWCE0-eI-k/UcF7a572DWI/AAAAAAAAA5w/moIet2K-acU/s320/inicios.jpg",
  "http://2.bp.blogspot.com/-cI8-e_XWuws/UcF7T5WULSI/AAAAAAAAA5o/rbBmo6-3WJc/s320/serenidad.jpg",
  "http://1.bp.blogspot.com/-y1QhoUXjSx8/UcF8AtR38AI/AAAAAAAAA54/Wthu4M1vJEQ/s320/abundancia.jpg",
  "http://3.bp.blogspot.com/-Y4859hz76VI/UcHrwLISmCI/AAAAAAAAA6Y/sga-EThHlMQ/s320/libertad.jpg",
  "http://4.bp.blogspot.com/-ugP4y8PP1nU/UcH5MgFGDpI/AAAAAAAAA6o/8c8l6rxwV4M/s320/amistad.jpg",
  "http://4.bp.blogspot.com/-fxhC7inJdew/UcH5TcTFiAI/AAAAAAAAA6w/noMOupRIdqg/s320/confianza.jpg",
  "http://3.bp.blogspot.com/-tryoiXKdx-8/UcIB3xGl8eI/AAAAAAAAA7I/D9B3X418QrQ/s320/gratitud.jpg",
  "http://4.bp.blogspot.com/-s1iYwWJJEv8/UcIBvBmzAFI/AAAAAAAAA7A/S2umiPGIXGQ/s320/seguridad.jpg",
  "http://4.bp.blogspot.com/-MNLViJTo8Wo/UcICYi0SURI/AAAAAAAAA7U/D36CP9euoPE/s320/compasion.jpg",
  "http://3.bp.blogspot.com/-fE0GsfjetRg/UcICfYzM0rI/AAAAAAAAA7c/6MjW4ndXpfg/s1600/extasis.jpg",
  "http://2.bp.blogspot.com/-H0y3dqWZNYo/UcIDP0P1jtI/AAAAAAAAA7g/NUvur9eUxzA/s320/romance.jpg",
  "http://3.bp.blogspot.com/-__FR8jS1TJA/UcIDaJNPhjI/AAAAAAAAA7o/58moxoNZrfY/s320/rendicion.jpg"
];

let nomeCartas = [
  "<strong>1-Gabriel (Divine Messenger) </strong> - BALANCE",
  "<strong>2-Gabriel (Divine Messenger) </strong> - BLESSING",
  "<strong>3-Gabriel (Divine Messenger) </strong> - ELEGANCE",
  "<strong>4-Gabriel (Divine Messenger) </strong> - INSPIRATION",
  "<strong>5-Hanael (Sacred Warrior) </strong> - COURAGE",
  "<strong>6-Hanael (Sacred Warrior) </strong> - HOPE",
  "<strong>7-Hanael (Sacred Warrior) </strong> - INTEGRITY",
  "<strong>8-Hanael (Sacred Warrior) </strong> - WILLPOWER",
  "<strong>9-Jophiel (Sacred Liberator) </strong> - CLEMENCY",
  "<strong>10-Jophiel (Sacred Liberator) </strong> - JOY",
  "<strong>11-Jophiel (Sacred Liberator) </strong> - RELEASE",
  "<strong>12-Jophiel (Sacred Liberator) </strong> - MEDITATION",
  "<strong>13-Metatron (Superior Master) </strong> - DIVINE INTELLIGENCE",
  "<strong>14-Metatron (Superior Master) </strong> - MERCY",
  "<strong>15-Metatron (Superior Master) </strong> - MIRACLES",
  "<strong>16-Metatron (Superior Master) </strong> - WISDOM",
  "<strong>17-Michael (Cosmic Leader) </strong> - ENCHANTMENT",
  "<strong>18-Michael (Cosmic Leader) </strong> - I AM PRESENCE",
  "<strong>19-Michael (Cosmic Leader) </strong> - TRANSMUTATION",
  "<strong>20-Michael (Cosmic Leader) </strong> - PATIENCE",
  "<strong>21-Rafael (Sacred Healer) </strong> - CLEANING",
  "<strong>22-Rafael (Sacred Healer) </strong> - COMMUNION",
  "<strong>23-Rafael (Sacred Healer) </strong> - STRENGTH OF THE EARTH",
  "<strong>24-Rafael (Sacred Healer) </strong> - EMPATHY",
  "<strong>25-Raziel (Divine Mysteries) </strong> - DREAMS",
  "<strong>26-Raziel (Divine Mysteries) </strong> -FAITH",
  "<strong>27-Raziel (Divine Mysteries) </strong> -INTUITION",
  "<strong>28-Raziel (Divine Mysteries) </strong> -WITHDRAWAL",
  "<strong>29-Sandalfon (Sacred Guardian) </strong> -EVOLUTION",
  "<strong>30-Sandalfon (Sacred Guardian) </strong> -INTENTION",
  "<strong>31-Sandalfon (Sacred Guardian) </strong> -LOVE",
  "<strong>32-Sandalfon (Sacred Guardian) </strong> -PLANETARY CYCLES",
  "<strong>33-Samael (Divine Guide) </strong> - BEGINNING",
  "<strong>34-Samael (Divine Guide) </strong> - SERENITY",
  "<strong>35-Uriel (Divine Companion) </strong> - ABUNDANCE",
  "<strong>36-Uriel (Divine Companion) </strong> - FREEDOM",
  "<strong>37-Uriel (Divine Companion) </strong> - FRIENDSHIP",
  "<strong>38-Uriel (Divine Companion) </strong> - CONFIDENCE",
  "<strong>39-Zadkiel (Divine Confort) </strong> - GRATITUDE",
  "<strong>40-Zadkiel (Divine Confort) </strong> - SECURITY",
  "<strong>41-Zaphkiel (Sacred Lover) </strong> - COMPASSION",
  "<strong>42-Zaphkiel (Sacred Lover) </strong> - ECSTASY",
  "<strong>43-Zaphkiel (Sacred Lover) </strong> - ROMANCE",
  "<strong>44-Zaphkiel (Sacred Lover) </strong> - SURRENDER"
];

//Código para as cartas pré-estabelecidos
for (var indice = 0; indice < listaCartas.length; indice++) {
  document.write(
    "<div class='divImg'><img src='" +
      listaCartas[indice] +
      "' class='grow'></img><div class='overlay'><div class='text'>" +
      nomeCartas[indice] +
      "</div></div></div>"
  );
}